version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/Employee-Jenkins:/project  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    restart: unless-stopped

  employee_management:
    build: 
      context: /home/ec2-user/Employee-Jenkins  # Full path to match volume
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /home/ec2-user/Employee-Jenkins:/app  # Match Jenkins volume
    depends_on:
      - employee_db
    environment:
      - DJANGO_SETTINGS_MODULE=employee.settings

  employee_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: