version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    # Remove container_name: jenkins-service
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    restart: unless-stopped

  employee_management:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - employee_db

  employee_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db