version: '3.8'
services:
  employee_management:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - employee_db
  employee_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db

