version: '3.8'

services:
  # jenkins:
  #   image: jenkins/jenkins:lts-jdk17
  #   user: root
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   volumes:
  #     - /mnt/jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /home/ec2-user/Employee-Jenkins:/app
  #   environment:
  #     - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
  #   restart: unless-stopped

  employee_management:
    container_name: employee_management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - . :/app
    environment:
      - DJANGO_SETTINGS_MODULE=employee_management.settings
      - PYTHONPATH=/app
    depends_on:
      employee_db:
        condition: service_healthy

  employee_db:
    container_name: employee_db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d employee_db"]
      interval: 60s
      timeout: 60s
      retries: 5

volumes:
  pg_data: